/** @jsx jsx */
import { jsx } from "@emotion/core";

import {
  Adapt,
  ChevronRight,
  ChevronLeft,
  Close,
  Ear,
  Easytoread,
  Search,
  SignLanguage,
  Volume,
  Otherlang,
  Ecc,
  Arrow,
  Burger,
  External,
  Exclamationmark,
  Check,
  Oval,
  LinkArrow,
  ArrowFat,
  Filter,
  List,
  Picturelist,
  Clear,
  Camera,
  Play,
  FileExcel,
  FilePdf,
  FilePowerpoint,
  FileWord,
  File,
  Warn,
  Question,
  AirTime,
  AtBranch,
  BankAccount,
  CallCenter,
  HomeDelivery,
  Online,
  Send,
  Settings,
  Logo,
  MegamenuCompany,

  // Editor Icons

  AppsAndGames,
  Auction,
  BeautyEngagement,
  Bullhorn,
  Leaf,
  Hardhat,
  BrokerServices,
  Cars,
  Clothes,
  Complaint,
  ComputerTvGameConsole,
  ConcertAndEvent,
  ConsumerRights,
  ContractWorkHouses,
  Craftsman,
  DistanceContractLaw,
  EducationAndCourses,
  ElectricityHeatingContract,
  FurnituresAndDecoration,
  GymAndWorkoutService,
  Hairdresser,
  Insurance,
  InternetFiberBroadband,
  LoanSaveInvest,
  LotteryAndGames,
  MobilePhone,
  MoveAndCleaningService,
  NotDefinedPicture,
  Pets,
  PurchaseFromPrivate,
  Receipt,
  SalesLaw,
  Telemarketing,
  Travel,
  WhiteGoods,
  Withdrawal,
  Pen,
  Map,
  ChatWithUs,
  CallUs,
  Mic,
  DatingServices,
  UserInjured,
  BabyCarriage,
  Ellipsis,
  HandHeart,
  Snowboarding,
} from "@konsumentverket-sverige/designsystem.utils"

const systemIconDefinitions = {
  Adapt,
  AirTime,
  Arrow,
  ArrowFat,
  AtBranch,
  BankAccount,
  Burger,
  CallCenter,
  Camera,
  Check,
  ChevronLeft,
  ChevronRight,
  Clear,
  Close,
  Ear,
  Easytoread,
  Ecc,
  Exclamationmark,
  External,
  File,
  FileExcel,
  FilePdf,
  FilePowerpoint,
  FileWord,
  Filter,
  HomeDelivery,
  LinkArrow,
  List,
  Logo,
  MegamenuCompany,
  Online,
  Otherlang,
  Oval,
  Picturelist,
  Play,
  Question,
  Search,
  Send,
  Settings,
  SignLanguage,
  Volume,
  Warn
};

const editorIconDefinitions = {
  AppsAndGames,
  Auction,
  BabyCarriage,
  BeautyEngagement,
  BrokerServices,
  Bullhorn,
  CallUs,
  Cars,
  ChatWithUs,
  Clothes,
  Complaint,
  ComputerTvGameConsole,
  ConcertAndEvent,
  ConsumerRights,
  ContractWorkHouses,
  Craftsman,
  DatingServices,
  DistanceContractLaw,
  EducationAndCourses,
  ElectricityHeatingContract,
  Ellipsis,
  FurnituresAndDecoration,
  GymAndWorkoutService,
  Hairdresser,
  HandHeart,
  Hardhat,
  Insurance,
  InternetFiberBroadband,
  Leaf,
  LoanSaveInvest,
  LotteryAndGames,
  Map,
  Mic,
  MobilePhone,
  MoveAndCleaningService,
  NotDefinedPicture,
  Pen,
  Pets,
  PurchaseFromPrivate,
  Receipt,
  SalesLaw,
  Snowboarding,
  Telemarketing,
  Travel,
  UserInjured,
  WhiteGoods,
  Withdrawal
}

const Icon = ({ icon, className, style, title, ...otherAttr }) => {
  const concatenatedIcons = {...systemIconDefinitions, ...editorIconDefinitions};
  const Element = concatenatedIcons[icon];

  if (Element === undefined) {
    return null;
  }

  return (
    <Element
      focusable="false"
      title={title || icon || ""}
      className={className}
      style={style}
      role="img"
      aria-label={title || icon || ""}
      {...otherAttr}
    />
  );
};

export { Icon, systemIconDefinitions, editorIconDefinitions };
